# name: beta
# description: "Runs terraform beta"
# on:
#   workflow_run:
#     workflows:
#       - Terraform Plan Preview              # Exactly match the `name:` in publish.yml
#     types:
#       - completed 

# # if: >
# #       github.event.workflow_run.conclusion == 'success' &&
# #       github.event.workflow_run.event == 'release'
# # on:
# #   pull_request

# # on:
# #   push:
# #     tags:
# #       - '^[0-9]{2}-[0-9]{2}-[0-9]{2}\.[0-9]{2}-[0-9]{2}$'

# # on:
# #   release:
# #     types: [published]

# # on:
# #   push:
# #     branches: 
# #       - feat/ENG-1178-automated-tag-based-deployment

# # permissions:
# #   contents: read
# #   pull-requests: write


# jobs:
#   beta:
#     if: github.event.workflow_run.conclusion == 'success'
    
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - uses: actions/download-artifact@v3
#         with:
#           name: release-tag

#       - name: Read tag
#         id: tag
#         run: |
#           TAG=$(cat tag.txt)
#           echo "TAG_ID=$TAG" >> $GITHUB_ENV
#       - name: echo tag
#         run: echo "using tag, $TAG_ID"

#       - name: Run Terraform Deploy from oak-release-actions
#         uses: oaknational/oak-release-actions/actions/terraform_pr_plan@feat/multi-comment-for-multi-subdir
#         with:
#           TF_BASE_SUBDIRECTORY: "api"
#           TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
#           TF_WORKSPACE: curr-kofo
#           TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
#           # TAG_ID: ${{ github.ref_name }}
#           TAG_ID: ${{env.TAG_ID}}


# # name: Apply to Beta
# # description: "Automated Beta release"

# # on:
# #   push:
# #     tags:
# #       - 'v*'
# # # on:
# # #   pull_request:

# # env:
# #   # TF_CLOUD_ORGANIZATION: "oak-national-academy"
# #   TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
# #   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
# #   TF_WORKSPACE: "curr-kofo"
# #   CONFIG_DIRECTORY: "infrastructure/api"

# # permissions:
# #   contents: read

# # jobs:
# #   beta_apply:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout code
# #         uses: actions/checkout@v3

# #       - name: Set tag_id from Git ref
# #         run: |
# #           echo "TF_VAR_tag_id=\"${{ github.ref_name }}\"" >> $GITHUB_ENV
# #           echo "Set TF_VAR_tag_id to ${{ github.ref_name }}"

# #       - name: Upload Configuration
# #         uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
# #         id: apply-upload
# #         with:
# #           workspace: ${{ env.TF_WORKSPACE }}
# #           directory: ${{ env.CONFIG_DIRECTORY }}
      
# #       - name: Create Apply Run
# #         uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
# #         id: apply-run
# #         with:
# #           workspace: ${{ env.TF_WORKSPACE }}
# #           configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

# #       - name: Apply
# #         uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
# #         id: apply
# #         with:
# #           run: ${{ steps.apply-run.outputs.run_id }}
# #           comment: " Staging Apply Run from GitHub Actions CI ${{ github.sha }}"
    